import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { beforeAll, describe, expect, it } from 'vitest';
import { preflightBuildArtifacts } from '../../../scripts/lib/token-build-preflight.mjs';
import { loadBuildGraph } from '../../../scripts/lib/token-build-graph.mjs';
import { generateTypedTokenModule } from '../../../scripts/lib/token-artifacts.mjs';

const repoRoot = process.cwd();
const stagedCssArtifactPath = path.join(repoRoot, 'design-tokens/dist/css/tokens.css');
const typedArtifactPath = path.join(repoRoot, 'design-tokens/dist/tokens.ts');
const figmaArtifactPath = path.join(repoRoot, 'design-tokens/dist/figma/tokens.json');
const runtimeCssArtifactPath = path.join(repoRoot, 'src/lib/tokens/tokens.css');

beforeAll(() => {
  execFileSync('pnpm', ['build:tokens'], {
    cwd: repoRoot,
    stdio: 'pipe',
  });
});

describe('generated token artifacts', () => {
  it('exports the stable typed surface and mirrors the current recipe payload', async () => {
    const generated = await import('../../../design-tokens/dist/tokens');
    const graph = loadBuildGraph();
    const typedSource = fs.readFileSync(typedArtifactPath, 'utf8');

    expect(Object.keys(generated).sort()).toEqual(['recipeMap', 'themeRegistry', 'tokenMap']);
    expect(typedSource).toMatch(
      /export type ThemeId = \(typeof themeRegistry\.themes\)\[number\]\[['"]id['"]\];/
    );
    expect(typedSource).toContain('export type TokenId = keyof typeof tokenMap;');
    expect(typedSource).toContain('export type RecipeComponentId = keyof typeof recipeMap;');
    expect(generated.recipeMap.button).toEqual(graph.recipeMap.button);
  });

  it('keeps the figma export token-only and DTCG-shaped', () => {
    const figma = JSON.parse(fs.readFileSync(figmaArtifactPath, 'utf8')) as Record<string, unknown>;

    expect(Object.keys(figma)).toEqual(['$extensions', 'core', 'motion', 'semantic']);
    expect(figma).not.toHaveProperty('recipeMap');
    expect(JSON.stringify(figma)).not.toContain('"componentId"');
  });

  it('emits lexical ordering for css vars, token map keys, and figma json keys', async () => {
    const generated = await import('../../../design-tokens/dist/tokens');
    const css = fs.readFileSync(stagedCssArtifactPath, 'utf8');
    const figma = JSON.parse(fs.readFileSync(figmaArtifactPath, 'utf8')) as Record<string, unknown>;

    const cssVariables = [...css.matchAll(/^\s*(--[a-z0-9-]+):/gm)].map((match) => match[1]);

    expect(cssVariables).toEqual(
      [...cssVariables].sort((left, right) => left.localeCompare(right))
    );
    expect(Object.keys(generated.tokenMap)).toEqual(
      [...Object.keys(generated.tokenMap)].sort((left, right) => left.localeCompare(right))
    );
    expectObjectKeysSorted(figma);
  });

  it('publishes the stable runtime css file with the generated banner and legacy aliases', () => {
    const runtimeCss = fs.readFileSync(runtimeCssArtifactPath, 'utf8');

    expect(
      runtimeCss.startsWith(
        '/* This file is generated by pnpm build:tokens. Do not edit by hand. */'
      )
    ).toBe(true);
    expect(runtimeCss).toContain('--semantic-color-background-base: #171717;');
    expect(runtimeCss).toContain('--color-background-base: var(--semantic-color-background-base);');
    expect(runtimeCss).toContain('--color-text-secondary: var(--semantic-color-text-secondary);');
    expect(runtimeCss).toContain(
      '--color-statusstrip-success: var(--semantic-color-status-strip-success);'
    );
    expect(runtimeCss).toContain(
      '--color-background-white-10: var(--semantic-color-background-white-10);'
    );
  });

  it('reports the public runtime css path in build:tokens json mode', () => {
    const result = execFileSync('node', ['design-tokens/build/build-tokens.mjs', '--json'], {
      cwd: repoRoot,
      encoding: 'utf8',
      stdio: 'pipe',
    });
    const payload = JSON.parse(result) as {
      ok: boolean;
      artifacts: Array<{ id: string; path: string; status: string }>;
    };

    expect(payload.ok).toBe(true);
    expect(payload.artifacts).toContainEqual(
      expect.objectContaining({
        id: 'runtime-css',
        path: 'src/lib/tokens/tokens.css',
        status: 'unchanged',
      })
    );
  });

  it('keeps outputs byte-stable on a second build', () => {
    const firstPass = readArtifacts();

    execFileSync('pnpm', ['build:tokens'], {
      cwd: repoRoot,
      stdio: 'pipe',
    });

    expect(readArtifacts()).toEqual(firstPass);
  });

  it('changes only the recipe section when recipe source data changes', async () => {
    const graph = loadBuildGraph();
    const originalSource = await generateTypedTokenModule(graph);
    const modifiedGraph = {
      ...graph,
      recipeMap: {
        ...graph.recipeMap,
        button: {
          ...graph.recipeMap.button,
          defaults: {
            ...graph.recipeMap.button.defaults,
            state: 'hover',
          },
        },
      },
    };
    const modifiedSource = await generateTypedTokenModule(modifiedGraph);

    expect(extractConstSection(originalSource, 'tokenMap')).toBe(
      extractConstSection(modifiedSource, 'tokenMap')
    );
    expect(extractConstSection(originalSource, 'recipeMap')).not.toBe(
      extractConstSection(modifiedSource, 'recipeMap')
    );
  });

  it('flags runtime css publication targets that are not writable files', () => {
    const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'token-preflight-'));
    const blockingDirectory = path.join(tempRoot, 'runtime-css');
    fs.mkdirSync(blockingDirectory);

    const diagnostics = preflightBuildArtifacts({
      repoRoot,
      artifacts: [
        {
          id: 'runtime-css',
          kind: 'css',
          relPath: 'src/lib/tokens/tokens.css',
          absPath: blockingDirectory,
        },
      ],
    });

    fs.rmSync(tempRoot, { recursive: true, force: true });

    expect(diagnostics).toEqual([
      expect.objectContaining({
        code: 'ARTIFACT_PATH_UNWRITABLE',
        path: 'src/lib/tokens/tokens.css',
        rule: 'CT-5',
      }),
    ]);
  });
});

function readArtifacts() {
  return {
    runtime: fs.readFileSync(runtimeCssArtifactPath, 'utf8'),
    stagedCss: fs.readFileSync(stagedCssArtifactPath, 'utf8'),
    figma: fs.readFileSync(figmaArtifactPath, 'utf8'),
    typed: fs.readFileSync(typedArtifactPath, 'utf8'),
  };
}

function extractConstSection(source: string, exportName: string) {
  const start = source.indexOf(`export const ${exportName} = `);
  const end = source.indexOf(' as const;', start);
  return source.slice(start, end + ' as const;'.length);
}

function expectObjectKeysSorted(value: unknown) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return;
  }

  const keys = Object.keys(value);
  expect(keys).toEqual([...keys].sort((left, right) => left.localeCompare(right)));
  for (const child of Object.values(value)) {
    expectObjectKeysSorted(child);
  }
}
