// Generated by ds-skills. Do not edit; run explicit project setup to refresh.

// src/project-host/entry.mjs
import fs9 from "node:fs";
import path9 from "node:path";
import { fileURLToPath } from "node:url";

// src/project-host/invoke.mjs
import path6 from "node:path";
import { spawnSync } from "node:child_process";

// src/project-host/state.mjs
import fs7 from "node:fs";
import path5 from "node:path";

// src/install/integrity.mjs
import fs2 from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

// src/install/record.mjs
import fs from "node:fs";

// src/figma/profile.mjs
var CannotEvaluateError = class extends Error {
  constructor(code, message) {
    super(message);
    this.name = "CannotEvaluateError";
    this.code = code;
  }
};

// src/install/record.mjs
var releasePlatforms = [
  "macos_arm64",
  "macos_x86_64",
  "linux_x86_64",
  "linux_aarch64",
  "windows_x86_64"
];
var digestPattern = /^[a-f0-9]{64}$/;
function releaseError(code, message) {
  return new CannotEvaluateError(code, message);
}
function readReleaseRecord(file) {
  let record;
  try {
    record = JSON.parse(fs.readFileSync(file, "utf8"));
  } catch (error) {
    throw releaseError(
      "RELEASE_RECORD_INPUT",
      `Cannot read release record ${file}: ${error.message}`
    );
  }
  return validateReleaseRecord(record);
}
function validateReleaseRecord(record) {
  const fail = (message) => {
    throw releaseError("RELEASE_RECORD_INVALID", message);
  };
  if (!object(record) || record.recordVersion !== "2")
    fail(
      "A version-2 release record with sealed payload manifest is required; upgrade the reviewed pin, do not bypass integrity"
    );
  if (typeof record.repository !== "string" || !/^[A-Za-z0-9][A-Za-z0-9_-]*\/[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(
    record.repository
  ))
    fail("Invalid release repository");
  if (typeof record.release !== "string" || !/^v\d+\.\d+\.\d+(?:-[0-9A-Za-z][0-9A-Za-z.-]*)?$/.test(record.release))
    fail("Invalid release identifier");
  if (typeof record.sourceCommit !== "string" || !/^[a-f0-9]{40}$/.test(record.sourceCommit))
    fail("Release sourceCommit must be a full Git SHA");
  const asset = (value, name) => {
    if (!object(value) || value.asset !== name || typeof value.sha256 !== "string" || !digestPattern.test(value.sha256))
      fail(`Invalid ${name} digest record`);
  };
  asset(record.bootstrap, "install.sh");
  asset(record.bootstrapPowershell, "install.ps1");
  asset(record.checksums, "SHA256SUMS");
  asset(record.payloadManifest, "payload-manifest.json");
  if (!object(record.assets) || Object.keys(record.assets).some((key) => !releasePlatforms.includes(key)))
    fail("Invalid release platform assets");
  for (const platform of releasePlatforms)
    asset(
      record.assets[platform],
      `ds-skills-${record.release}-${platform}.${platform.startsWith("windows") ? "zip" : "tar.gz"}`
    );
  return record;
}
function platformKey(platform = process.platform, arch = process.arch) {
  const value = {
    "darwin/arm64": "macos_arm64",
    "darwin/x64": "macos_x86_64",
    "linux/x64": "linux_x86_64",
    "linux/arm64": "linux_aarch64",
    "win32/x64": "windows_x86_64"
  }[`${platform}/${arch}`];
  if (!value)
    throw releaseError(
      "RELEASE_PLATFORM_UNSUPPORTED",
      `No tested release for ${platform}/${arch}. Supported: ${releasePlatforms.join(", ")}`
    );
  return value;
}
function object(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

// src/install/integrity.mjs
var digestOf = (bytes) => crypto.createHash("sha256").update(bytes).digest("hex");
function verifyInstalledFiles(home, record, platform = process.platform) {
  const diagnostics = [];
  const bad = (code, message, file) => diagnostics.push({ code, message, path: file });
  const manifestName = record.payloadManifest.asset;
  const manifestPath = path.join(home, manifestName);
  let manifest;
  try {
    requireRegular(manifestPath);
    const bytes = fs2.readFileSync(manifestPath);
    if (digestOf(bytes) !== record.payloadManifest.sha256) {
      bad(
        "RELEASE_MANIFEST_DIGEST",
        "Installed manifest differs from the reviewed digest",
        manifestName
      );
      return diagnostics;
    }
    manifest = JSON.parse(bytes);
    validateManifest(manifest, record);
  } catch (error) {
    bad("RELEASE_MANIFEST_INVALID", error.message, manifestName);
    return diagnostics;
  }
  const expectedDirs = /* @__PURE__ */ new Set([""]);
  for (const file of Object.keys(manifest.files)) {
    let parent = path.posix.dirname(file);
    while (parent !== ".") {
      expectedDirs.add(parent);
      parent = path.posix.dirname(parent);
    }
  }
  const seen = /* @__PURE__ */ new Set();
  function visit(directory, relative = "") {
    for (const name of fs2.readdirSync(directory).sort()) {
      const rel = relative ? `${relative}/${name}` : name;
      const target2 = path.join(directory, name);
      const info2 = fs2.lstatSync(target2);
      if (info2.isSymbolicLink()) {
        bad(
          "RELEASE_CONTENT_LINK",
          "Installed payload must not contain symbolic links",
          rel
        );
        continue;
      }
      if (info2.isDirectory()) {
        if (!expectedDirs.has(rel))
          bad(
            "RELEASE_CONTENT_EXTRA",
            "Unlisted directory in installed payload",
            rel
          );
        else visit(target2, rel);
        continue;
      }
      if (rel === manifestName) continue;
      const expected = manifest.files[rel];
      if (!expected) {
        bad("RELEASE_CONTENT_EXTRA", "Unlisted installed file", rel);
        continue;
      }
      seen.add(rel);
      if (!info2.isFile()) {
        bad(
          "RELEASE_CONTENT_KIND",
          "Installed entry is not a regular file",
          rel
        );
        continue;
      }
      if (digestOf(fs2.readFileSync(target2)) !== expected.sha256)
        bad(
          "RELEASE_CONTENT_DIGEST",
          "Installed bytes differ from the sealed manifest",
          rel
        );
      if (platform !== "win32" && expected.executable && !(info2.mode & 73))
        bad(
          "RELEASE_EXECUTABLE_MODE",
          "Required launcher has no executable mode",
          rel
        );
    }
  }
  try {
    visit(home);
  } catch (error) {
    bad("RELEASE_CONTENT_UNREADABLE", error.message, home);
  }
  for (const file of Object.keys(manifest.files))
    if (!seen.has(file))
      bad(
        "RELEASE_CONTENT_MISSING",
        "Required installed file is missing",
        file
      );
  return diagnostics;
}
function validateManifest(value, record) {
  if (!object(value) || value.manifestVersion !== "1" || value.release !== record.release || value.sourceCommit !== record.sourceCommit || !object(value.files) || !Object.keys(value.files).length)
    throw new Error("Invalid installed manifest shape or release identity");
  for (const [file, spec] of Object.entries(value.files)) {
    if (!safePath(file) || file === record.payloadManifest.asset || !object(spec) || typeof spec.sha256 !== "string" || !digestPattern.test(spec.sha256) || typeof spec.executable !== "boolean")
      throw new Error(`Invalid installed manifest file entry: ${file}`);
  }
  for (const file of [
    "bin/ds-skills",
    "bin/ds-skills.cmd",
    "lib/bin/ds-skills.mjs",
    "lib/release.json",
    "lib/skills/RELEASE.json",
    "lib/package.json"
  ])
    if (!Object.hasOwn(value.files, file))
      throw new Error(`Manifest omits required entry ${file}`);
}
function safePath(value) {
  return value.length > 0 && !value.includes("\\") && !value.includes(":") && !value.startsWith("/") && value.split("/").every((s) => s && s !== "." && s !== "..") && [...value].every((s) => s.charCodeAt(0) >= 32);
}
function requireRegular(file) {
  if (!fs2.lstatSync(file).isFile())
    throw new Error("Installed manifest is missing or not a regular file");
}

// src/install/resolve.mjs
import fs3 from "node:fs";
import os from "node:os";
import path2 from "node:path";
function installPrefix(env = process.env, platform = process.platform) {
  const prefix = env.DS_SKILLS_PREFIX || (platform === "win32" ? path2.join(
    env.LOCALAPPDATA || path2.join(os.homedir(), "AppData", "Local"),
    "ds-skills"
  ) : path2.join(env.HOME || os.homedir(), ".local", "share", "ds-skills"));
  return path2.resolve(prefix);
}
function resolveRelease({
  recordPath,
  record,
  prefix = installPrefix(),
  platform = process.platform,
  arch = process.arch
}) {
  const pin = record === void 0 ? readReleaseRecord(recordPath) : validateReleaseRecord(record);
  const selected = platformKey(platform, arch);
  const home = path2.join(path2.resolve(prefix), pin.release);
  const executable = path2.join(
    home,
    "bin",
    platform === "win32" ? "ds-skills.cmd" : "ds-skills"
  );
  const context = {
    release: pin.release,
    sourceCommit: pin.sourceCommit,
    platform: selected,
    prefix: path2.resolve(prefix),
    home,
    executable,
    skillsDir: path2.join(home, "lib", "skills")
  };
  let info2;
  try {
    info2 = fs3.lstatSync(home);
  } catch (error) {
    if (error.code === "ENOENT")
      throw releaseError(
        "RELEASE_NOT_INSTALLED",
        `${pin.release} is not installed at ${home}. Install the reviewed pin explicitly; no PATH fallback is permitted.`
      );
    throw releaseError("RELEASE_INSTALL_UNREADABLE", error.message);
  }
  if (!info2.isDirectory() || info2.isSymbolicLink())
    return {
      ok: false,
      ...context,
      diagnostics: [
        {
          code: "RELEASE_HOME_KIND",
          message: "Release home must be a real directory, not a symlink or file",
          path: home
        }
      ]
    };
  const diagnostics = verifyInstalledFiles(home, pin, platform);
  if (!diagnostics.length) {
    for (const [file, code] of [
      ["lib/release.json", "RELEASE_IDENTITY_MISMATCH"],
      ["lib/skills/RELEASE.json", "RELEASE_SKILL_SKEW"]
    ]) {
      try {
        const identity = JSON.parse(
          fs3.readFileSync(path2.join(home, file), "utf8")
        );
        if (identity?.release !== pin.release || identity?.sourceCommit !== pin.sourceCommit)
          throw new Error(
            "Sealed CLI and skills identities must agree with the reviewed pin"
          );
      } catch (error) {
        diagnostics.push({ code, message: error.message, path: file });
      }
    }
  }
  return { ok: !diagnostics.length, ...context, diagnostics };
}

// src/project-host/paths.mjs
import fs4 from "node:fs";
import path3 from "node:path";
var launcherPath = ".ds-skills/project.mjs";
var receiptPath = ".ds-skills/installation.json";
var pinPath = "ds-skills.release.json";
function hostError(message) {
  return releaseError("PROJECT_INSTALLATION", message);
}
function info(file) {
  try {
    return fs4.lstatSync(file);
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}
function fileBytes(file) {
  const stat = info(file);
  if (!stat) return null;
  if (!stat.isFile() || stat.isSymbolicLink())
    throw hostError(`Expected a regular file: ${file}`);
  return fs4.readFileSync(file);
}
function projectPaths(root) {
  let resolved;
  try {
    resolved = fs4.realpathSync(root);
  } catch (error) {
    throw hostError(`Cannot resolve project root: ${error.message}`);
  }
  if (!fs4.statSync(resolved).isDirectory())
    throw hostError("Project root must be a directory");
  const directory = path3.join(resolved, ".ds-skills");
  const stat = info(directory);
  if (stat && (!stat.isDirectory() || stat.isSymbolicLink()))
    throw hostError(
      `Expected a real project installation directory: ${directory}`
    );
  return {
    root: resolved,
    directory,
    pin: path3.join(resolved, pinPath),
    launcher: path3.join(resolved, launcherPath),
    receipt: path3.join(resolved, receiptPath)
  };
}
function equalBytes(left, right) {
  return left === null || right === null ? left === right : left.equals(right);
}

// src/project-host/assets.mjs
import fs5 from "node:fs";
import path4 from "node:path";
var surfaces = [".agents", ".claude"];
var reserved = /^(?:con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i;
function safeSegments(relative) {
  return typeof relative === "string" && relative.split("/").every(
    (part) => /^[a-zA-Z0-9_.-]+$/.test(part) && part !== "." && part !== ".." && !part.endsWith(".") && !reserved.test(part)
  );
}
function managedRoot(relative) {
  if (relative === ".ds-skills/project.mjs") return null;
  const [surface, group, name, ...rest] = relative.split("/");
  if (!safeSegments(relative) || !surfaces.includes(surface))
    throw hostError(`Invalid managed output path: ${relative}`);
  if (group === "skills" && /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name) && rest.length)
    return `${surface}/skills/${name}`;
  if (["schemas", "templates"].includes(group) && name)
    return `${surface}/${group}`;
  throw hostError(
    `Output is outside managed skill or support roots: ${relative}`
  );
}
function parentDirectories(files) {
  const directories = /* @__PURE__ */ new Set();
  for (const relative of files) {
    let parent = path4.posix.dirname(relative);
    while (parent !== ".") {
      directories.add(parent);
      parent = path4.posix.dirname(parent);
    }
  }
  return directories;
}
function confinedPath(root, relative) {
  if (!safeSegments(relative))
    throw hostError(`Unsafe installation path: ${relative}`);
  const parts = relative.split("/");
  for (let i = 1; i <= parts.length; i++) {
    const file = path4.join(root, ...parts.slice(0, i)), stat = info(file);
    if (stat && !fs5.readdirSync(path4.dirname(file)).includes(parts[i - 1]))
      throw hostError(`Case-aliased output path: ${file}`);
    if (i < parts.length && stat && (!stat.isDirectory() || stat.isSymbolicLink()))
      throw hostError(`Expected a real output parent: ${file}`);
  }
  return path4.join(root, ...parts);
}
function readTree(root, manifest, group) {
  const entries = {};
  function visit(directory, relative = "") {
    const stat = info(directory);
    if (!stat?.isDirectory() || stat.isSymbolicLink())
      throw hostError(
        `Missing or non-directory release asset group: ${directory}`
      );
    for (const name of fs5.readdirSync(directory).sort()) {
      const key = relative ? `${relative}/${name}` : name, file = path4.join(directory, name);
      if (!safeSegments(key))
        throw hostError(`Unsupported release asset name: ${key}`);
      const child = info(file);
      if (child?.isDirectory() && !child.isSymbolicLink()) visit(file, key);
      else {
        const bytes = fileBytes(file), spec = manifest.files[`lib/${group}/${key}`];
        if (!bytes || !spec || digestOf(bytes) !== spec.sha256)
          throw hostError(
            `Release asset changed after verification: ${group}/${key}`
          );
        entries[key] = { bytes, executable: spec.executable };
      }
    }
  }
  visit(root);
  if (!Object.keys(entries).length)
    throw hostError(`Release asset group is empty: ${root}`);
  return entries;
}
function releaseSkillAssets(home, manifestDigest) {
  const bytes = fileBytes(path4.join(home, "payload-manifest.json"));
  if (!bytes || digestOf(bytes) !== manifestDigest)
    throw hostError("Release manifest changed after verification");
  const manifest = JSON.parse(bytes);
  const root = path4.join(home, "lib"), skills = path4.join(root, "skills"), groups = {};
  const names = [];
  for (const name of fs5.readdirSync(skills).sort()) {
    if (name === "RELEASE.json") continue;
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name) || reserved.test(name))
      throw hostError(`Unsupported skill directory: ${name}`);
    const tree = readTree(path4.join(skills, name), manifest, `skills/${name}`);
    if (!tree["SKILL.md"]?.bytes.length)
      throw hostError(`Skill ${name} needs a nonempty SKILL.md`);
    groups[`skills/${name}`] = tree;
    names.push(name);
  }
  if (!names.length)
    throw hostError("The selected release has no discoverable skills");
  for (const group of ["schemas", "templates"])
    groups[group] = readTree(path4.join(root, group), manifest, group);
  const files = /* @__PURE__ */ new Map(), folded = /* @__PURE__ */ new Set();
  for (const surface of surfaces)
    for (const [group, entries] of Object.entries(groups))
      for (const [name, asset] of Object.entries(entries)) {
        const key = `${surface}/${group}/${name}`;
        if (folded.has(key.toLowerCase()))
          throw hostError(`Case-colliding release asset: ${key}`);
        folded.add(key.toLowerCase());
        files.set(key, asset);
      }
  validateOutputPaths([...files.keys()]);
  return { names, files };
}
function validateOutputPaths(files) {
  const folded = /* @__PURE__ */ new Set();
  for (const file of files) {
    managedRoot(file);
    if (folded.has(file.toLowerCase()))
      throw hostError(`Case-colliding output path: ${file}`);
    folded.add(file.toLowerCase());
  }
  for (const directory of parentDirectories(files))
    if (folded.has(directory.toLowerCase()))
      throw hostError(`File/directory collision: ${directory}`);
}

// src/project-host/receipt.mjs
function readReceipt(bytes) {
  if (bytes === null) return null;
  try {
    const value = JSON.parse(bytes), version = value?.installationVersion;
    const keys = [
      "installationVersion",
      "release",
      "sourceCommit",
      "pinSha256",
      version === "1" ? "launcherSha256" : "files"
    ];
    if (!object(value) || !["1", "2"].includes(version) || Object.keys(value).length !== keys.length || Object.keys(value).some((key) => !keys.includes(key)) || typeof value.release !== "string" || !/^v\d+\.\d+\.\d+(?:-[0-9A-Za-z][0-9A-Za-z.-]*)?$/.test(value.release) || typeof value.sourceCommit !== "string" || !/^[a-f0-9]{40}$/.test(value.sourceCommit) || typeof value.pinSha256 !== "string" || !digestPattern.test(value.pinSha256))
      throw new Error("Unrecognized installation receipt");
    if (version === "1") {
      if (typeof value.launcherSha256 !== "string" || !digestPattern.test(value.launcherSha256))
        throw new Error("Invalid launcher digest");
      return {
        ...value,
        files: {
          [launcherPath]: { sha256: value.launcherSha256, executable: false }
        }
      };
    }
    if (!object(value.files) || !Object.hasOwn(value.files, launcherPath))
      throw new Error("Missing owned-file manifest");
    validateOutputPaths(Object.keys(value.files));
    for (const [file, entry] of Object.entries(value.files)) {
      if (!object(entry) || Object.keys(entry).length !== 2 || typeof entry.sha256 !== "string" || !digestPattern.test(entry.sha256) || typeof entry.executable !== "boolean")
        throw new Error(`Invalid file digest/mode: ${file}`);
    }
    return value;
  } catch (error) {
    throw hostError(`Invalid installation receipt: ${error.message}`);
  }
}

// src/project-host/managed.mjs
import fs6 from "node:fs";
function readOutput(root, relative) {
  const file = confinedPath(root, relative), bytes = fileBytes(file);
  if (bytes === null) return null;
  return {
    sha256: digestOf(bytes),
    executable: process.platform === "win32" ? false : Boolean(info(file).mode & 73)
  };
}
function matches(actual, expected) {
  return actual === null || expected === null ? actual === expected : actual.sha256 === expected.sha256 && (process.platform === "win32" || actual.executable === expected.executable);
}
function inspectRoots(root, files) {
  const keys = new Set(files), directories = parentDirectories(files), seenDirectories = [];
  const roots = [...new Set(files.map(managedRoot).filter(Boolean))].sort();
  function visit(relative) {
    const file = confinedPath(root, relative), stat = info(file);
    if (!stat) return;
    if (!stat.isDirectory() || stat.isSymbolicLink())
      throw hostError(`Expected a real managed asset directory: ${file}`);
    seenDirectories.push(relative);
    for (const name of fs6.readdirSync(file).sort()) {
      const key = `${relative}/${name}`, child = confinedPath(root, key), entry = info(child);
      if (entry?.isSymbolicLink())
        throw hostError(`Refusing symbolic managed content: ${child}`);
      if (entry?.isDirectory()) {
        if (!directories.has(key))
          throw hostError(
            `Unowned directory inside managed asset root: ${child}`
          );
        visit(key);
      } else if (!keys.has(key))
        throw hostError(`Unowned file inside managed asset root: ${child}`);
    }
  }
  for (const relative of roots) visit(relative);
  return seenDirectories.sort();
}
function outputDiagnostics(desired, prior) {
  const diagnostics = [];
  for (const [relative, expected] of Object.entries(desired.receipt.files)) {
    try {
      if (!matches(readOutput(desired.paths.root, relative), expected))
        diagnostics.push({
          code: "PROJECT_OUTPUT_SKEW",
          path: relative,
          message: "Missing or changed installed output; run explicit project setup"
        });
    } catch (error) {
      diagnostics.push({
        code: "PROJECT_OUTPUT_KIND",
        path: relative,
        message: error.message
      });
    }
  }
  const all = [
    .../* @__PURE__ */ new Set([
      ...Object.keys(desired.receipt.files),
      ...Object.keys(prior?.files ?? {})
    ])
  ];
  try {
    inspectRoots(desired.paths.root, all);
  } catch (error) {
    diagnostics.push({
      code: "PROJECT_UNOWNED_CONTENT",
      path: desired.paths.root,
      message: error.message
    });
  }
  for (const relative of Object.keys(prior?.files ?? {})) {
    if (Object.hasOwn(desired.receipt.files, relative)) continue;
    try {
      if (readOutput(desired.paths.root, relative))
        diagnostics.push({
          code: "PROJECT_STALE_OUTPUT",
          path: relative,
          message: "Previously owned output is no longer selected; explicit setup is required"
        });
    } catch (error) {
      diagnostics.push({
        code: "PROJECT_STALE_OUTPUT",
        path: relative,
        message: error.message
      });
    }
  }
  return diagnostics;
}

// src/project-host/state.mjs
function desiredInstallation(root, prefix) {
  const paths = projectPaths(root), pinBytes = fileBytes(paths.pin);
  if (!pinBytes) throw hostError(`Missing reviewed pin: ${paths.pin}`);
  let record;
  try {
    record = validateReleaseRecord(JSON.parse(pinBytes));
  } catch (error) {
    throw hostError(`Invalid reviewed pin: ${error.message}`);
  }
  const release = resolveRelease({ record, prefix });
  if (!release.ok)
    throw hostError(
      `Selected release failed verification: ${release.diagnostics.map((d) => d.code).join(", ")}`
    );
  const relative = path5.relative(fs7.realpathSync(release.home), paths.root);
  if (relative === "" || !relative.startsWith(`..${path5.sep}`) && relative !== ".." && !path5.isAbsolute(relative))
    throw hostError(
      "A project cannot be installed inside its selected immutable release"
    );
  const launcher = fileBytes(
    path5.join(release.home, "lib/dist/project-host/launcher.mjs")
  );
  if (!launcher)
    throw hostError("Selected release does not contain a project launcher");
  const assets = releaseSkillAssets(
    release.home,
    record.payloadManifest.sha256
  ), files = assets.files;
  files.set(launcherPath, { bytes: launcher, executable: false });
  const receipt = {
    installationVersion: "2",
    release: record.release,
    sourceCommit: record.sourceCommit,
    pinSha256: digestOf(pinBytes),
    files: Object.fromEntries(
      [...files.keys()].sort().map((file) => [
        file,
        {
          sha256: digestOf(files.get(file).bytes),
          executable: files.get(file).executable
        }
      ])
    )
  };
  return {
    paths,
    record,
    release,
    pinBytes,
    launcher,
    files,
    skills: assets.names,
    receipt,
    receiptBytes: Buffer.from(`${JSON.stringify(receipt, null, 2)}
`)
  };
}
function checkProjectInstallation({ root, prefix }) {
  return checkDesiredInstallation(desiredInstallation(root, prefix));
}
function checkDesiredInstallation(desired) {
  const diagnostics = [];
  let prior;
  try {
    const bytes = fileBytes(desired.paths.receipt);
    prior = readReceipt(bytes);
    if (!equalBytes(bytes, desired.receiptBytes))
      diagnostics.push({
        code: "PROJECT_RECEIPT_SKEW",
        path: desired.paths.receipt,
        message: "Missing or changed installed output receipt; run explicit project setup"
      });
  } catch (error) {
    diagnostics.push({
      code: "PROJECT_RECEIPT_INVALID",
      path: desired.paths.receipt,
      message: error.message
    });
  }
  diagnostics.push(...outputDiagnostics(desired, prior));
  if (!equalBytes(fileBytes(desired.paths.pin), desired.pinBytes))
    diagnostics.push({
      code: "PROJECT_PIN_CHANGED",
      path: desired.paths.pin,
      message: "Reviewed pin changed during project verification"
    });
  return {
    ok: diagnostics.length === 0,
    root: desired.paths.root,
    release: desired.record.release,
    sourceCommit: desired.record.sourceCommit,
    skills: desired.skills,
    installedFileCount: desired.files.size,
    diagnostics
  };
}

// src/project-host/invoke.mjs
function target(root, prefix, verifyProject) {
  const desired = desiredInstallation(root, prefix);
  if (verifyProject) {
    const check = checkDesiredInstallation(desired);
    if (!check.ok)
      throw hostError(
        check.diagnostics.map((d) => `${d.path}: ${d.message}`).join("\n")
      );
  }
  return desired;
}
function runPinnedAt(root, args, { prefix, verifyProject = true, capture = false } = {}) {
  if (!Array.isArray(args) || args.some((arg) => typeof arg !== "string"))
    throw hostError("CLI arguments must be strings");
  const desired = target(root, prefix, verifyProject);
  const child = spawnSync(
    process.execPath,
    [path6.join(desired.release.home, "lib/bin/ds-skills.mjs"), ...args],
    {
      cwd: desired.paths.root,
      env: { ...process.env, DS_SKILLS_PREFIX: desired.release.prefix },
      stdio: capture ? ["ignore", "pipe", "pipe"] : "inherit",
      encoding: "utf8",
      maxBuffer: 16 * 1024 * 1024
    }
  );
  if (child.error || child.signal || child.status === null)
    throw hostError(
      `Pinned command did not complete: ${child.error?.message ?? child.signal ?? "no status"}`
    );
  return {
    status: child.status,
    stdout: child.stdout ?? "",
    stderr: child.stderr ?? ""
  };
}
function readPinnedResultAt(root, args, expectedCommand, options = {}) {
  if (typeof expectedCommand !== "string" || !/^[a-z]+(?: [a-z]+)*$/.test(expectedCommand) || !Array.isArray(args) || !expectedCommand.split(" ").every((part, index) => args[index] === part))
    throw hostError(
      "Machine caller must specify the exact requested command identity"
    );
  const child = runPinnedAt(
    root,
    args.includes("--json") ? args : [...args, "--json"],
    { ...options, verifyProject: true, capture: true }
  );
  if (child.status !== 0 && child.status !== 1)
    throw hostError(
      `Pinned command could not evaluate (exit ${child.status}): ${child.stderr.trim()}`
    );
  let result;
  try {
    result = JSON.parse(child.stdout);
  } catch {
    throw hostError("Pinned command did not return a single JSON result");
  }
  if (!result || Array.isArray(result) || result.resultVersion !== "1" || result.command !== expectedCommand || typeof result.ok !== "boolean" || result.ok !== (child.status === 0))
    throw hostError(
      "Pinned command result version, identity or conformance disagrees with its exit status"
    );
  return { evaluated: true, status: child.status, result };
}

// src/project-host/provision.mjs
import path8 from "node:path";

// src/install/acquire.mjs
import { execFileSync } from "node:child_process";
import crypto2 from "node:crypto";
import fs8 from "node:fs";
import os2 from "node:os";
import path7 from "node:path";
function releaseBaseUrl(record) {
  return `https://github.com/${record.repository}/releases/download/${record.release}`;
}
async function acquireRelease({
  record,
  prefix,
  platform = process.platform,
  arch = process.arch,
  baseUrl,
  fetchBytes = downloadBytes,
  run = executeBootstrap
}) {
  validateReleaseRecord(record);
  platformKey(platform, arch);
  if (typeof prefix !== "string" || !prefix.length)
    throw releaseError("RELEASE_PREFIX", "An installation prefix is required");
  const bootstrap = platform === "win32" ? record.bootstrapPowershell : record.bootstrap;
  const base = baseUrl ?? releaseBaseUrl(record);
  let parsed;
  try {
    parsed = new URL(base);
  } catch {
    throw releaseError("RELEASE_MIRROR", "Invalid release mirror URL");
  }
  if (!["http:", "https:"].includes(parsed.protocol) || parsed.username || parsed.password || parsed.search || parsed.hash)
    throw releaseError(
      "RELEASE_MIRROR",
      "Release mirror must be an unauthenticated HTTP(S) base URL without query or fragment"
    );
  const url = `${base.replace(/\/$/, "")}/${bootstrap.asset}`;
  const bytes = await fetchBytes(url);
  const digest = crypto2.createHash("sha256").update(bytes).digest("hex");
  if (digest !== bootstrap.sha256)
    throw releaseError(
      "RELEASE_BOOTSTRAP_DIGEST",
      `Bootstrap differs from the reviewed digest. Expected ${bootstrap.sha256}; received ${digest}. Nothing was executed or installed.`
    );
  const work = fs8.mkdtempSync(path7.join(os2.tmpdir(), "ds-skills-acquire-"));
  const file = path7.join(work, bootstrap.asset);
  try {
    fs8.writeFileSync(file, bytes, { flag: "wx", mode: 448 });
    await run({ file, prefix: path7.resolve(prefix), platform, baseUrl: base });
  } finally {
    fs8.rmSync(work, { recursive: true, force: true });
  }
  return { asset: bootstrap.asset, url, digest };
}
async function downloadBytes(url) {
  let response;
  try {
    response = await fetch(url, {
      redirect: "follow",
      signal: globalThis.AbortSignal.timeout(6e4)
    });
  } catch (error) {
    throw releaseError(
      "RELEASE_DOWNLOAD",
      `Cannot download bootstrap: ${error.message}`
    );
  }
  if (!response.ok)
    throw releaseError(
      "RELEASE_DOWNLOAD",
      `Cannot download ${url}: HTTP ${response.status}`
    );
  try {
    return Buffer.from(await response.arrayBuffer());
  } catch (error) {
    throw releaseError(
      "RELEASE_DOWNLOAD",
      `Cannot read bootstrap response: ${error.message}`
    );
  }
}
function executeBootstrap({ file, prefix, platform, baseUrl }) {
  const command = platform === "win32" ? "powershell" : "bash";
  const args = platform === "win32" ? ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", file] : [file];
  try {
    execFileSync(command, args, {
      env: {
        ...process.env,
        DS_SKILLS_PREFIX: prefix,
        DS_SKILLS_BASE_URL: baseUrl
      },
      stdio: ["ignore", "pipe", "pipe"]
    });
  } catch (error) {
    throw releaseError(
      "RELEASE_INSTALL_FAILED",
      `Verified bootstrap failed: ${error.stderr?.toString().trim() || error.message}`
    );
  }
}

// src/project-host/provision.mjs
async function provisionProject({
  root,
  prefix = installPrefix(),
  baseUrl = process.env.DS_SKILLS_BASE_URL,
  capture = false
}) {
  if (Number(process.versions.node.split(".")[0]) < 22)
    throw hostError("Project installation requires Node 22 or newer");
  const paths = projectPaths(root), pinBytes = fileBytes(paths.pin);
  if (!pinBytes) throw hostError(`Missing reviewed pin: ${paths.pin}`);
  let record;
  try {
    record = validateReleaseRecord(JSON.parse(pinBytes));
  } catch (error) {
    throw hostError(`Invalid reviewed pin: ${error.message}`);
  }
  let release;
  try {
    release = resolveRelease({ record, prefix });
  } catch (error) {
    if (error.code !== "RELEASE_NOT_INSTALLED") throw error;
  }
  if (!release?.ok) await acquireRelease({ record, prefix, baseUrl });
  const samePin = () => {
    if (!equalBytes(fileBytes(paths.pin), pinBytes))
      throw hostError("Reviewed pin changed during project acquisition/setup");
  };
  samePin();
  const command = runPinnedAt(
    paths.root,
    ["project", "setup", "--root", paths.root],
    { prefix, capture, verifyProject: false }
  );
  samePin();
  if (command.status !== 0) return command;
  const check = checkProjectInstallation({ root: paths.root, prefix });
  samePin();
  if (!check.ok)
    throw hostError(
      "Selected setup exited successfully without establishing the complete project installation"
    );
  return {
    ...command,
    root: paths.root,
    release: record.release,
    sourceCommit: record.sourceCommit,
    prefix: path8.resolve(prefix),
    home: path8.join(path8.resolve(prefix), record.release),
    launcher: paths.launcher
  };
}

// src/project-host/entry.mjs
var moduleFile = fileURLToPath(import.meta.url);
var boundRoot = path9.dirname(path9.dirname(moduleFile));
function runPinned(args, options) {
  return runPinnedAt(boundRoot, args, { ...options, verifyProject: true });
}
function readPinnedResult(args, expectedCommand, options) {
  return readPinnedResultAt(boundRoot, args, expectedCommand, options);
}
async function main(args) {
  if (args[0] === "--install") {
    if (args.length !== 1)
      throw hostError(
        "Use --install alone; DS_SKILLS_PREFIX and DS_SKILLS_BASE_URL select acquisition locations"
      );
    return (await provisionProject({ root: boundRoot })).status;
  }
  if (args[0] === "--check") {
    if (args.length !== 1) throw hostError("Use --check alone");
    return runPinned(["project", "check", "--root", boundRoot]).status;
  }
  if (args[0]?.startsWith("-") && !["--help", "--version", "-h", "-V"].includes(args[0]))
    throw hostError(`Unknown launcher option: ${args[0]}`);
  return runPinned(args).status;
}
function isMain() {
  try {
    return Boolean(process.argv[1]) && fs9.realpathSync(process.argv[1]) === fs9.realpathSync(moduleFile);
  } catch {
    return false;
  }
}
if (isMain()) {
  try {
    process.exitCode = await main(process.argv.slice(2));
  } catch (error) {
    process.stderr.write(
      `[${error.code ?? "PROJECT_LAUNCH_FAILED"}] ${error.message}
`
    );
    process.exitCode = error.name === "CannotEvaluateError" ? 2 : 3;
  }
}
export {
  readPinnedResult,
  runPinned
};
